spring:
  application:
    name: kafka-streams-demo
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: ${ORACLE_DRIVER}
    url: ${ORACLE_DB_URL}
    username: ${ORACLE_DB_USER}
    password: ${ORACLE_DB_PASS}
    hikari:
      pool-name: KafkaStreamsHikariPool
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 60000
      max-lifetime: 1800000
      auto-commit: false
      connection-test-query: SELECT 1 FROM DUAL
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        order_updates: true
        order_inserts: true
        format_sql: false
        jdbc:
          batch_size: 50
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      security.protocol: SASL_PLAINTEXT
      sasl.mechanism: PLAIN
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username=${KAFKA_USERNAME} password=${KAFKA_PASSWORD};
  cloud:
    function:
      definition: orderRouter;paymentRouter;orderDlqRouter;paymentDlqRouter;orderCreatedEventConsumer
    stream:
      kafka:
        binder:
          consumer-properties:
            auto.offset.reset: earliest
            key.deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
            value.deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
            max.poll.interval.ms: 300000
            session.timeout.ms: 30000
            heartbeat.interval.ms: 3000
            enable.auto.commit: false
            spring.json.trusted.packages: '*'
            spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
            spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
          producer-properties:
            key.serializer: org.apache.kafka.common.serialization.StringSerializer
            value.serializer: org.springframework.kafka.support.serializer.JsonSerializer
        bindings:
          orderRouter-in-0:
            consumer:
              ack-mode: record
              enable-dlq: true
              dlq-name: order-dlt
          paymentRouter-in-0:
            consumer:
              ack-mode: record
              enable-dlq: true
              dlq-name: payment-dlt
          orderDlqRouter-in-0:
            consumer:
              ack-mode: record
              enable-dlq: true
              dlq-name: order-dlt
          paymentDlqRouter-in-0:
            consumer:
              ack-mode: record
              enable-dlq: true
              dlq-name: payment-dlt
      bindings:
        sendOrderEvent-out-0:
          destination: order
        sendPaymentEvent-out-0:
          destination: payment
        orderRouter-in-0:
          destination: order
          group: ${application.messaging.consumer-group-order}
#          consumer:
#            max-attempts: 1
        paymentRouter-in-0:
          destination: payment
          group: ${application.messaging.consumer-group-payment}
#          consumer:
#            max-attempts: 1
        orderDlqRouter-in-0:
          destination: order-dlt
          group: ${application.messaging.consumer-group-order-dlq}
          consumer:
            max-attempts: 3
            back-off-initial-interval: 2000
            back-off-multiplier: 3
            back-off-max-interval: 10000
        paymentDlqRouter-in-0:
          destination: payment-dlt
          group: ${application.messaging.consumer-group-payment-dlq}
          consumer:
            max-attempts: 3
            back-off-initial-interval: 2000
            back-off-multiplier: 3
            back-off-max-interval: 10000

application:
  messaging:
    consumer-group-order: order-group
    consumer-group-order-dlq: order-group-dlt
    consumer-group-payment: payment-group
    consumer-group-payment-dlq: payment-group-dlt
